module.exports = {
  DIR: 'directoryPath',
  MAX_FILE_SIZE: process.env.MAX_FILE_SIZE * 1024 * 1024 || 104857600, // 100 MiB
  OBJECT_TYPE: 'objectType',
  EVENT_TYPES: 'eventTypes',
  ID: 'id',
  UNIQUE_CRITERIA: 'uniqueCriteria',
  EMPTY_RESULT: 'allowEmptyResult',
  OMITTED_CRITERIA: 'allowCriteriaToBeOmitted',
  END_TIME: 'endTime',
  START_TIME: 'startTime',
  MIN_DATE: -8640000000000000,
  MAX_DATE: 8640000000000000,
  BEHAVIOUR: 'emitBehaviour',
  EMIT_INDIVIDUALLY: 'emitIndividually',
  FETCH_ALL: 'fetchAll',
  FETCH_PAGE: 'fetchPage',
  SINGLE_PAGE_PER_INTERVAL: 'singlePagePerInterval',
  PAGE_SIZE: 'pageSize',
  PAGE_NUMBER: 'pageNumber',
  MAX_RESULT_SIZE: 'maxResultSize',
  NUM_SEARCH_TERMS: 'numSearchTerms',
  ORDER: 'order',
  ITEMS_TO_LOOKUP: 'itemsToLookup',
  RESULTS_DICTIONARY: 'resultsDictionary',
  WAIT_FOR_OBJECT_TO_EXIST: 'waitForObjectToExist',
};
